class_name EventTypes
extends RefCounted


enum Type {
	COMBAT_STARTED,
	TURN_STARTED,
	TURN_ENDED,

	ACTION_STARTED,
	ACTION_COMPLETED,
	ACTION_CANCELLED,

	MOVE_STARTED,
	POSITION_CHANGED,
	MOVE_COMPLETED,

	ATTACK_STARTED,
	ATTACK_HIT,
	ATTACK_MISS,

	DAMAGE_APPLIED,
	EFFECT_APPLIED,
	EFFECT_EXPIRED,
	EFFECT_DAMAGE_APPLIED,
	EFFECT_HEAL_APPLIED,
	EFFECT_RESOURCE_CHANGED,
	FAITH_CHANGED,
	ABILITY_TRIGGERED,
	ABILITY_STACKS_CLEARED,
	ABILITY_COOLDOWN_REDUCED,
	SKILL_CAST,
	SKILL_COOLDOWN_REDUCED,
	EQUIPMENT_CHANGED,
	INTERRUPTION_STARTED,
	REACTION_AVAILABLE,
	REACTION_TRIGGERED,
	REACTION_DECLINED,
	INTERRUPTION_ENDED,

	COMBAT_VICTORY,
	COMBAT_DEFEAT
}
